os: linux
dist: bionic
sudo: false
language: cpp
compiler:
  - gcc

install:
  # Install conan
  - pip install conan
  # Automatic detection of arch, compiler, etc.
  - conan user

script:
  # Out-of-source build
  - mkdir "build"
  - cd build
  # Install third-party libraries
  - conan install ../conanfile.txt
  # Configure the build system with tests enabled
  - cmake -G"Unix Makefiles" -DCMAKE_MODULE_PATH=$(pwd) -DENABLE_TESTS=True ../CMakeLists.txt
  # Build
  - cmake --build .
  # Run all the tests
  - ctest .
