os: linux
dist: bionic
sudo: false
language: cpp
compiler:
  - gcc

install:
  # Install conan
  - pip install conan
  # Automatic detection of arch, compiler, etc.
  - conan user

before_script:
  # Out-of-source build
  - mkdir "build"
  - cd build
  # Install third-party libraries
  - conan install ../conanfile.txt

script:
  # Configure the build system with tests enabled
  - cmake -G"Unix Makefiles" -DCMAKE_MODULE_PATH=$PWD -DENABLE_TESTS=True ..
  # Build
  - cmake --build .

after_success:
  # Run all the tests
  - ctest .
